### ISSUE TITLE
Implement design for Signin and LangSettings screens

### ISSUE THREAD

**Issue by VadimCpp** [VadimCpp/alias-online#25]

**Comment by sealione1311** [comment]
![photo_2022-10-22_14-00-54](https://user-images.githubusercontent.com/44976901/197335536-e1d8a90c-a5fb-4947-af14-ddb0f0d37b6c.jpg)
![photo_2022-10-22_14-00-49](https://user-images.githubusercontent.com/44976901/197335539-4b0d59c8-cfdf-4200-bd8c-fa65660443bc.jpg)
![photo_2022-10-22_14-00-44](https://user-images.githubusercontent.com/44976901/197335549-6e8c9437-7352-4557-a994-a9de241000ff.jpg)
![photo_2022-10-22_14-00-25](https://user-images.githubusercontent.com/44976901/197335552-06aed302-1b9e-4424-86a3-61176ab62bda.jpg)
