### ISSUE TITLE
Implement language switcher

### ISSUE THREAD

**Issue by VadimCpp** [VadimCpp/alias-online#4]
Implement language switcher

Design:
https://www.figma.com/file/6cgqcwEl6X2ZzgvRiI8YRn/Alias-online?node-id=1%3A5

Sources:
https://github.com/VadimCpp/alias-online

**Comment by Kislax** [comment]
I'm doing the task, I've done the logic.
Do this task with new design?
Can I create components - for a new design?

and pictures
![image](https://user-images.githubusercontent.com/50524488/195717946-4ade76a6-fc2e-4108-8827-b48c4d1bd311.png)
![image](https://user-images.githubusercontent.com/50524488/195717969-83817f75-01b8-41a0-b00f-1c3a139183ba.png)

**Comment by VadimCpp** [comment]
That is enough for the task. Please send PR.
Later we update design as a separate task.
